### ISSUE TITLE
API 키에 대하여

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#2]
https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

**Never deploy your key in client-side environments like browsers or mobile apps.**

Exposing your OpenAI API key in client-side environments like browsers or mobile apps allows malicious users to take that key and make requests on your behalf – which may lead to unexpected charges or compromise of certain account data. _**Requests should always be routed through your own backend server where you can keep your API key secure.**_

API key를 현재 앱에서 불러오는 방식 대신 **_backend 서버_**를 열고 request, resopones 받는 방식으로 바꿔야 배포에 문제가 없다고 합니다?!

또한 이런식으로 서버 요청으로 바꿨을 때, _**Chatting쪽 로직을 수정**_해야 될 것 같아요

**Comment by vmkmym** [comment]
이건 한다면 gpt부터 해봐야될 것 같네요
