### ISSUE TITLE
Ref : 중복코드 함수화로 코드 재사용성 증가

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#20]
CommentScreen에 Alert이랑 MyNovelScreen이랑 같음  
  
Alert 내용을 받아오는 함수로 만들어서 어디에 써두면 될 듯

**Comment by vmkmym** [comment]
Development에 작업 브랜치 선택할 수 있어요 신기하죠

**Comment by vmkmym** [comment]
아 깃허브 생각할수록 천재적이네요... 이번 겨울에 깃, 깃헙 마스터해보죠

**Comment by hongmyeoun** [comment]
좋아요!
