### ISSUE TITLE
Fix : Delete 버그

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#21]
Delete를 하고 나면 Box에 위치가 원위치로 돌아오지 않고 로티가 계속 돌아가는 문제  
  
Delete 되면 Box의 위치를 원상태 해야할 것 같음

**Comment by vmkmym** [comment]
어느 부분 버그에요? 글 목록 지울 때 그런 버그가 있었나요?

**Comment by hongmyeoun** [comment]
모든 부분에서 슬라이드 하면 지울 수 있잖아요
지우고 나면 그 글만 사라지고 글 목록이 정상적으로 보여야 하는데
삭제를 하면 글 목록이 슬라이드 된 상태로 보여요

**Comment by vmkmym** [comment]
아 엄청난 버그가 있었네요 알겠습니다!

**Comment by hongmyeoun** [comment]
로직 변경으로 해결
