### ISSUE TITLE
Ref: shared/UiFunctions -> 리팩토링하기

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#24]
## 문제점
- 아직 작업 시작 안함

## 리팩토링 방향
- SharedUiState.kt
- SharedModel.kt
- SharedViewModel.kt

**Comment by hongmyeoun** [comment]
Ui Functions 쪽은 비슷한 함수들이 많고, 사용처가 다양해서 작업 많이 힘들것 같은데 어떻게 진행하실 껀가요?

**Comment by vmkmym** [comment]
생각보다 작업 괜찮을 것 같아 다행이네요...
