### ISSUE TITLE
Ref : Merge 요청

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#25]
Library였던 폴더에 MVVM 구조 변경이 완성됐어요.
일단 여러 군데에서 쓰이는 Book, NovelInfo, RelayChatToNovelBook은 변경하지 않고 그대로 두었습니다.
[Delete 버그](https://github.com/KDT-villainlp/villainlp/issues/21)와 [조회수 버그](https://github.com/KDT-villainlp/villainlp/issues/26)가 있습니다.
이는 UiFunctions에서 다루고 있기 때문에 Conflict가 많이 생길 것 같아 현재까지의 작업 Merge요청 합니다.

**Comment by vmkmym** [comment]
Merge 완료했습니다.
