### ISSUE TITLE
Merge 요청

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#36]
novel package에 있는 파일들 MVVM 코드 구조 개선 및 UI 함수 리팩토링 완료했씁니다!
현재 상황에서 리팩토링을 더 진행하면 Conflict에서 고생할 것 같아 Merge 요청 드립니다!

기존 함수들에서 추가, 변경점이 많아 Conflict 가 우려되는데
-> 작동 잘 되니 그냥 이전 버전 다 지우고 Merge할 버전 코드를 붙여넣는 것도 방법일수도...

파이팅 🙏🙌

**Comment by vmkmym** [comment]
눈뜨면 merge할게여...

**Comment by vmkmym** [comment]
conflict 의외로 Navigator.kt 밖에 없었음

**Comment by hongmyeoun** [comment]
머지된 branch에 유의사항 있을까요?
일단 제가 작업한 부분은 이전이랑 기능이 바뀐게 없어서 문제는 없어요
안스버전을 올려야 된다고 했던거 같은데, 버전정보가 어떻게 돼요?

**Comment by vmkmym** [comment]
안스버전... 이구아나요

**Comment by vmkmym** [comment]
유의사항 없어요...
