### ISSUE TITLE
Bug : Firebase Database paths must not contain '.', '#', '$', '[', or ']'

### ISSUE THREAD

**Issue by hongmyeoun** [KDT-villainlp/villainlp#37]
com.google.firebase.database.DatabaseException: Invalid Firebase Database path: gpt3.5/테스트입니다. Firebase Database paths must not contain '.', '#', '$', '[', or ']'

```
    fun loadChatMessages(listener: (List<ChatMessage>) -> Unit, title: String, threadId: ThreadId?) {
        val database = Firebase.database
        val chatRef = database.getReference("gpt3.5/$title")
```

현재 UI가 다른 기기에서 얼마나 다른지 보려고 확인하다가 발견했습니다
현재 ChatListScreen에서 gemini와 채팅중인 채팅방에는 들어가 지지만 gpt와 채팅중인 채팅방엔 안들어가 지네요🤔

**Comment by vmkmym** [comment]
gpt3.5 에서 점 넣어서 그렇네요. 경로 바꾸고 안될 거라고 생각못하고 확인을 안했어요. 다른 경로 이름 지정하시고 작업하시면 될 것 같습니다.

**Comment by hongmyeoun** [comment]
네. gpt/$title로 할께요
