### ISSUE TITLE
feat: chat/GeminiAPI

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#4]
# [Android 앱 (클라이언트 SDK)에서 Gemini API 적용하기](https://ai.google.dev/tutorials/android_quickstart?hl=ko)

## Prompt design strategies

- [Google AI Studio](http://makersuite.google.com/?hl=ko)에서 프롬프트 엔지니어링 후 앱에 적용하기 -> #33 

```Kotlin
val generativeModel = GenerativeModel(
    // For text-only input, use the gemini-pro model
    modelName = "gemini-pro",
    // Access your API key as a Build Configuration variable (see "Set up your API key" above)
    apiKey = BuildConfig.apiKey
)

val chat = generativeModel.startChat(
    history = listOf(
        content(role = "user") { text("Hello, I have 2 dogs in my house.") },
        content(role = "model") { text("Great to meet you. What would you like to know?") }
    )
)

chat.sendMessage("How many paws are in my house?")


// Use streaming with multi-turn conversations (like chat)
val chat = generativeModel.startChat()
chat.sendMessageStream(inputContent).collect { chunk ->
    print(chunk.text)
}

// For multi-turn conversations (like chat)
val history = chat.history
val messageContent = content { text("This is the message I intend to send")}
val (totalTokens) = generativeModel.countTokens(*history.toTypedArray(), messageContent)

val config = generationConfig {
    temperature = 0.9f
    topK = 16
    topP = 0.1f
    maxOutputTokens = 200
    stopSequences = listOf("red")
}

val generativeModel = GenerativeModel(
    modelName = "MODEL_NAME",
    apiKey = BuildConfig.apiKey,
    generationConfig = config
)
```

**Comment by vmkmym** [comment]
### Class GeminiChatModel
1. threadId로 대화를 저장하고 불러오는 것이 아니라 title(채팅방 이름)만 받는 로직으로 함.
2. 채팅방 이름을 매개변수로 받아 새로운 채팅방을 생성하는 데 고유 ID를 반환하게 해서 대화를 저장하고 불러오기로 함.
3. 
```Kotlin
사용자가 채팅방의 제목을 입력하면, createChatRoom 메서드는 이 제목을 매개변수로 받아 새로운 채팅방을 생성합니다. 
이 메서드는 새로 생성된 채팅방의 고유 ID를 반환하며, 이 ID는 메시지를 저장하고 불러올 때 사용됩니다.  

saveChatMessage와 saveChatbotMessage 메서드는 메시지와 채팅방의 고유 ID를 매개변수로 받아 메시지를 저장합니다. 
이 메서드들은 고유 ID를 사용하여 메시지가 저장될 채팅방을 찾습니다.  

loadChatMessages와 loadChatbotMessages 메서드는 채팅방의 고유 ID를 매개변수로 받아 해당 채팅방의 메시지를 불러옵니다. 이 메서드들은 고유 ID를 사용하여 메시지를 불러올 채팅방을 찾습니다.  

이렇게 하면, 각 채팅방은 고유한 ID를 가지게 되므로, 채팅방의 제목이 같더라도 각 채팅방을 구분할 수 있습니다.
```

**Comment by vmkmym** [comment]
### `createChatRoom` 메서드를 `saveChatMessage`, `saveChatbotMessage`, `loadChatMessages`, `loadChatbotMessages` 메서드에서 직접 호출하는 것은 적절하지 않습니다.

1. `createChatRoom` 메서드는 채팅방을 생성하는 역할을 합니다. 메시지를 저장하거나 불러오는 과정에서 새로운 채팅방을 생성하는 것은 로직상 맞지 않습니다. 채팅방은 이미 생성된 상태에서 메시지를 저장하거나 불러와야 합니다.

2. `createChatRoom` 메서드가 채팅방의 고유 ID를 반환합니다. 이 ID는 메시지를 저장하거나 불러올 때 사용되는데, 이 과정이 `saveChatMessage`, `saveChatbotMessage`, `loadChatMessages`, `loadChatbotMessages` 메서드 내부에서 이루어지면, 각 메서드 호출마다 새로운 채팅방이 생성되고, 그로 인해 새로운 고유 ID가 반환됩니다. 이는 기존의 채팅방에 메시지를 저장하거나 불러오는 것이 아니라, 매번 새로운 채팅방에서 작업을 수행하게 됩니다.

따라서, 채팅방을 생성하는 `createChatRoom` 메서드는 채팅방을 생성하는 시점에 한 번만 호출되어야 하며, 그 반환값인 채팅방의 고유 ID는 메시지를 저장하거나 불러올 때 사용되어야 합니다.

**Comment by vmkmym** [comment]
### 문제점

- Gemini Chat 테스트를 하려면 CreativeGround 리팩토링을 먼저 해야할 듯
- 현재 로직은 채팅방을 만들 때 부터 Open AI assistand id를 생성하지만 gemini로 선택하게끔 하려면 비즈니스 로직과 UI로직은 완전 분리하는게 좋을 것 같음 
- AlertCard를 만들 때 gpt or gemini로 선택하게끔 해서 gpt를 선택하면 gpt와의 채팅이, gemini를 선택하면 gemini와의 채팅이 이어져야함

**Comment by vmkmym** [comment]
CreativeGround 리팩토링 했으나 boolean변수 때문에 나누면 기능 작동 X
최소한의 리팩토링만 끝냄

gemini도 적용했는데 test를 못해봄...
AlertCard를 수정해야 gemini 적용되는지 볼 수 있을 듯?

**Comment by vmkmym** [comment]
### title, threadId, assistId를 선택적으로 전달하고 싶은 문제점 발생 (ChattingList.kt)

navController.navigate 함수를 호출하여 새로운 화면으로 이동함. 이때, title, threadId, assistId 세 가지 인자를 모두 전달함.  

1. 1개의 인자만 전달하거나 3개의 인자가 있을 땐 3개 다 전달하거나...어떻게할까

**Comment by vmkmym** [comment]
## 드디어 해결한 문제 (ChattingList.kt)

```kotlin
.clickable {
                    if (novelInfo.threadId == "" || novelInfo.assistId == "") {
                        navController.navigate("GeminiChatScreen/${novelInfo.title}")
                    } else {
                        navController.navigate("ChattingScreen/${novelInfo.title}/${novelInfo.threadId}/${novelInfo.assistId}")
                    }
                }
``` 
1. novelInfo data class에서 threadId랑 assistId를 빈문자열로 선언해놓고 조건문에서 null이면 GeminiChatScreen으로 이동하게 함
그러니까 당연히 GeminiChatScreen으로 이동하지를 않는데 깨닫지 못하고 있었음.
2. novelInfo data class에서 threadId랑 assistId를 null값으로 하면 이동하려나? 싶었는데 생각해보니 조건문을 ""이렇게 선언해주면 될 것 같아서 해보니 됨.
3. 결론: 1개의 인자만 갖고 있으면 GeminiChatScreen, 3개의 인자를 갖고 있으면 ChattingScreen으로 이동하게 하며 문제 해결.

**Comment by vmkmym** [comment]
### 챗봇이 응답을 안하는 문제 -> 어디서 잘못된걸까

**1. 이 부분에서 geminiChatViewModel.sendMessage(input)를 호출하여 챗봇에 메시지를 보내고 있습니다.** 
- 이 함수가 챗봇에 메시지를 제대로 보내고 있는지 확인해야 합니다.  
- GeminiChatViewModel 클래스에서 sendMessage 함수를 찾아서 그 구현을 확인해 보세요. 
- 이 함수는 챗봇에 메시지를 보내고, 챗봇의 응답을 받아서 처리하는 로직을 포함해야 합니다. 
- 만약 이 부분에 문제가 있다면, 챗봇의 응답이 제대로 처리되지 않을 수 있습니다.  

**2. 또한, 챗봇 서비스가 제대로 동작하고 있는지 확인해 보세요. 챗봇 서비스에 문제가 있다면, 챗봇의 응답이 제대로 돌아오지 않을 수 있습니다.**  

**3. 마지막으로, 챗봇의 응답을 받아서 UI에 표시하는 로직도 확인해 보세요.** 
- geminiChatViewModel.loadChatbotMessages({ botmessages -> sentBotMessages = botmessages }, title) 이 부분에서 챗봇의 응답을 받아서 sentBotMessages에 저장하고 있습니다. 
- 이 sentBotMessages를 사용해서 UI에 챗봇의 응답을 표시하는 로직이 제대로 동작하고 있는지 확인해 보세요.

**Comment by vmkmym** [comment]
### User 정보가 있는데 왼쪽에서 메시지를 반복해서 보내는 문제

의심1. db 경로 문제?
의심2. 모르겠음

**Comment by hongmyeoun** [comment]
고생했어요~!!

**Comment by vmkmym** [comment]
초기 메시지를 user로 바꾸고 메시지가 2번 반복된 것 같은데...🤔

**Comment by vmkmym** [comment]
- Rollback으로 message 중복 문제 해결🤔
- GeminiChatViewModel sendMessage함수에서 model.saveChatMessage(geminiChatMessage, "chatRoomId")에서 chatRoomId를 createChatRoom에서 반환한 key값을 넣어줘야 하는데 그대로 둬서 gemini가 응답할 경로를 찾지 못함

**Comment by vmkmym** [comment]
fix: MODEL, ERROR 메시지를 구분해서 UI에 반영되게 하고 메시지의 길이에 따라 동적으로 말풍선의 길이를 조절하도록 수정

- 사용자가 하는 말을 못 알아듣는 상태, 그래도 뭔가 답이 온다

**Comment by vmkmym** [comment]
유저 메시지 구분하기 uid로 isCurrentUser 만들어야됨
user, model을 구분할 수 있게 만들기

**Comment by hongmyeoun** [comment]
startChat에서 role에 user가 필요
https://github.com/KDT-villainlp/villainlp/commit/e18301990a56062b17e4aa83590c54d04c4b80a2

**Comment by vmkmym** [comment]
대화 가능하니까 close 합니다?
프롬프트는 #33 에서 진행할게요!
