### ISSUE TITLE
Feat:ChatScreen 반응형 UI 적용하기

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#49]
## 문제 -> 해결
`Navigator.kt`에서 `startDestination`을 작업 중인 화면을 해놓으니까 로그인 정보가 없어서 앱이 죽었음

**Comment by vmkmym** [comment]
채팅방 만들어서 들어가면 앱이 죽는데,,,
이건 건들지도 않는데 왜 자꾸 죽지....

**Comment by vmkmym** [comment]
로그캣 에러 메시지에 따르면, 애플리케이션의 창이 제거되는 과정에서 문제가 발생한 것으로 보입니다. 이는 ChatListScreen.kt에서 채팅방을 클릭하여 새로운 화면으로 전환하려고 할 때 발생하는 것으로 추정됩니다.  이 문제를 해결하기 위해 다음 사항들을 확인해 보세요:  
ChatListScreen.kt에서 채팅방을 클릭했을 때 호출되는 코드가 올바르게 작성되었는지 확인하세요. 특히, 새로운 화면으로 전환하는 코드가 올바르게 작성되었는지 확인해 보세요.  
새로운 화면을 로드하는 과정에서 오류가 발생하지 않는지 확인하세요. 예를 들어, 새로운 화면의 onCreate 메서드에서 오류가 발생하거나, 필요한 리소스를 로드하지 못하는 경우 이런 문제가 발생할 수 있습니다.  
새로운 화면의 레이아웃 파일이 올바르게 작성되었는지 확인하세요. 레이아웃 파일에 오류가 있으면 화면이 제대로 로드되지 않을 수 있습니다.  
WindowManager 오류가 발생하는 시점의 로그를 자세히 확인하세요. 오류 메시지 또는 스택 트레이스에서 문제가 발생한 코드 위치를 찾을 수 있을 것입니다.  
이러한 사항들을 확인한 후에도 문제가 해결되지 않는다면, 문제가 발생하는 코드 부분을 좀 더 자세히 살펴봐야 할 것입니다.

**Comment by hongmyeoun** [comment]
firebase path 문제는 아닌가요? 2주전에 그거 때문에 gpt 채팅방에 들어갈 수 없었어요.
[gpt3.5/$title](https://github.com/KDT-villainlp/villainlp/blob/refactoring_mvvm/app/src/main/java/com/example/villainlp/chat/openAichat/ChatModel.kt)이어서 .이 들어가면 안될거예요.
path에 특수문자 . 없에면 될 꺼예요.

**Comment by vmkmym** [comment]
아 맞다.... 안바꿨다
