### ISSUE TITLE
Ref: MVVM

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#5]
# MVVM 패턴으로 Refactoring하기
- [앱 아키텍처 가이드](https://developer.android.com/jetpack/guide?hl=ko)를 참고하여 MVVM 패턴 적용하기

| <img width="350" alt="스크린샷 2024-01-22 오후 11 31 40" src="https://github.com/KDT-villainlp/villainlp/assets/71699054/3d4ba3f0-bb86-40a2-9ca5-a6d6eec49772"> | <img width="350" alt="스크린샷 2024-01-22 오후 11 31 45" src="https://github.com/KDT-villainlp/villainlp/assets/71699054/8a1bc378-e0de-453e-8fc5-ada035f610b7"> |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="350" alt="스크린샷 2024-01-22 오후 11 31 50" src="https://github.com/KDT-villainlp/villainlp/assets/71699054/4c2dc3b7-6b2f-48e5-922a-a479fbb29a01"> | <img width="350" alt="스크린샷 2024-01-22 오후 11 31 55" src="https://github.com/KDT-villainlp/villainlp/assets/71699054/61f5e174-cb45-44b7-92ba-51d5314590c1"> |

<img width="750" alt="스크린샷 2024-01-22 오후 11 37 15" src="https://github.com/KDT-villainlp/villainlp/assets/71699054/3570d49c-a3ef-4c70-86cb-514643d1d6dd">

**Comment by hongmyeoun** [comment]
1. Model
애플리케이션의 데이터와 비즈니스 로직을 담당하는 부분입니다.
DB, Network, File 등의 데이터 소스와 상호 작용하여 데이터를 가져오고 저장합니다.
ViewModel과 View는 Model에 직접적으로 접근할 수 없으며, Model은 View나 ViewModel의 존재를 알지 못합니다.
 
2. ViewModel
Model과 View 사이에서 중개자 역할을 수행하는 부분입니다.
View에 필요한 데이터를 Model로부터 가져와서 가공하거나 변환하여 View에 전달합니다.
View에서 발생하는 이벤트를 처리하고, Model로부터 데이터가 변경될 때마다 View에 이를 알려 View의 상태를 업데이트합니다.
View와의 상호작용과 생명주기를 관리합니다.
 
3. View
사용자 인터페이스를 담당합니다.
ViewModel로부터 전달받은 데이터를 사용하여 UI를 구성합니다.
이벤트가 발생하면 ViewModel에 전달합니다. 
View는 ViewModel에 대한 참조를 가지고 있지만, ViewModel은 View에 대한 참조를 가지고 있지 않습니다.

출처: [https://dev-musa.tistory.com/entry/한-번의-글로-이해하는-소프트웨어-아키텍처-패턴-MVC-MVP-MVVM](https://dev-musa.tistory.com/entry/%ED%95%9C-%EB%B2%88%EC%9D%98-%EA%B8%80%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EC%86%8C%ED%94%84%ED%8A%B8%EC%9B%A8%EC%96%B4-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%ED%8C%A8%ED%84%B4-MVC-MVP-MVVM) [Fun한 개발자 dev_stitch:티스토리]

**Comment by vmkmym** [comment]
setting 완료

**Comment by hongmyeoun** [comment]
Branch: refactoring_mvvm_library
- ☑️ ReadMyNovel 완료
- https://github.com/KDT-villainlp/villainlp/tree/refactoring_mvvm_library/app/src/main/java/com/example/villainlp/novel
