### ISSUE TITLE
Style: 반응형 UI 적용하기

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#7]
# [Navigation for responsive UIs](https://developer.android.com/guide/topics/large-screens/navigation-for-responsive-uis#compose)

![image](https://github.com/KDT-villainlp/villainlp/assets/71699054/5ac4493e-69ec-4c1f-b5f7-5b318aa9f355)

- [ ] 반응형 UI로 바꾸기
- [ ] 다크모드 적용하기
- [ ] 하드코딩 없애기

**Comment by vmkmym** [comment]
#5 번 작업 완료 후에 진행해야됨.

**Comment by hongmyeoun** [comment]
스크린 크기, 가로 세로, 다크 라이트 모드 고려하기

**Comment by hongmyeoun** [comment]
고려해야할 반응형 UI
0. 가로모드는 지원하지 않을 것
1. 스마트폰에서 UI가 항상 같을 것
2. 다크모드 라이트모드를 지원할 것
