### ISSUE TITLE
deploy: 배포하기

### ISSUE THREAD

**Issue by vmkmym** [KDT-villainlp/villainlp#8]
## 노블라블라 피드백 폼
- https://forms.gle/kvSvomFRhY2pHM896

## 노블라블라 문의 사이트
- https://sites.google.com/view/novelah-blah/%ED%99%88

## 노블라블라 개인정보처리방침
- [https://sites.google.com/view/novlahvlah-privacy/홈](https://sites.google.com/view/novlahvlah-privacy/%ED%99%88)

**Comment by vmkmym** [comment]
### list
- 개발자 계정 만들기
- 앱 이미지 만들기
- 앱 스크린샷
- 앱 상세 설명 작성하기
- realtime db 저장 루트 변경하기 (db초기화하기)
- firestore db 초기화하기

- 앱 배포 후 먼저 다운 받아보고 괜찮은지 확인하고
- 괜찮은 것 같으면 인텔인공지능방에 다운로드 링크 뿌리기

**Comment by vmkmym** [comment]
[Google Play 개발자 계정 등록](https://support.google.com/googleplay/android-developer/answer/6112435?hl=ko&ref_topic=3450769&sjid=14264950098722858480-AP)

[새로운 개인 개발자 계정의 앱 테스트 요구사항](https://support.google.com/googleplay/android-developer/answer/14151465)

**Comment by hongmyeoun** [comment]
![개발자계정](https://github.com/KDT-villainlp/villainlp/assets/139526068/2ebf0435-06d9-421b-ba82-25862f3b54f4)
개발자 계정 설정 신원 확인중입니다.

**Comment by vmkmym** [comment]
**[열심히 만든 어플을 구글 플레이 스토어에 배포 해 보자](https://velog.io/@anna_developer/%EC%97%B4%EC%8B%AC%ED%9E%88-%EB%A7%8C%EB%93%A0-%EC%96%B4%ED%94%8C%EC%9D%84-%EA%B5%AC%EA%B8%80-%ED%94%8C%EB%A0%88%EC%9D%B4-%EC%8A%A4%ED%86%A0%EC%96%B4%EC%97%90-%EB%B0%B0%ED%8F%AC-%ED%95%B4-%EB%B3%B4%EC%9E%90#2-%EA%B5%AC%EA%B8%80-%ED%94%8C%EB%A0%88%EC%9D%B4-%EC%BD%98%EC%86%94%EC%97%90-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%98%AC%EB%A6%AC%EA%B8%B0)**

**Comment by vmkmym** [comment]
## 비공개 테스터 구글 이메일 
- 20명 안모아져서 모르는 사람들한테 뿌릴까 생각 중임. 갤럭시 쓰는 사람들이 주변에 없음...

## 구글 이메일 리스트
[nuegnasmik0182@gmail.com](mailto:nuegnasmik0182@gmail.com), [yoojin1117@gmail.com](mailto:yoojin1117@gmail.com), [wjdgkfla2000@gmail.com](mailto:wjdgkfla2000@gmail.com), [mhj219@gmail.com](mailto:mhj219@gmail.com), [hong80714@gmail.com](mailto:hong80714@gmail.com), [qkrsnfl2360@gmail.com](mailto:qkrsnfl2360@gmail.com)
